name: ecommerce2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.1.8
  mockito: any
  equatable: any
  dartz: any
  get_it: any
  flutter_bloc: any
  shared_preferences: any
  meta: any
  rxdart: any
  bloc: any
  bloc_test: any
  intl: any
  uuid: any
  cupertino_icons: ^1.0.2
  internet_connection_checker: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_test: ^2.0.6

flutter:
  uses-material-design: true
